<?php 
$block = $this->getLayout()->createBlock('weeereport/adminhtml_weeereport');
$filter = $block->getFilterData();
$session = Mage::getSingleton('core/session'); 
?>
<div class="entry-edit">
   <form id="filter_form" action="<?php echo $this->getUrl('admin_weeereport/adminhtml_weeereport/generateReport'); ?>" method="get">
      <div></div>
      <div class="entry-edit-head">
         <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Filter");?></h4>
         <div class="form-buttons"></div>
      </div>
      <div class="fieldset " id="sales_report_base_fieldset">
         <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
               <tbody>
                  <tr>
                     <td colspan="2" class="hidden"><input id="sales_report_store_ids" name="store_ids" value="" type="hidden"></td>
                  </tr>
				  <tr>
					<td class="label"><?php echo $this->__('Select Stores:') ?></td>
					<td class="value"><?php echo $this->getChildHtml('store.switcher'); ?></td>
				  </tr>
				  <tr>
                     <td class="label"><label for="country"><?php echo $this->__("Country");?></label></td>
                     <td class="value">
                        <?php /* $_countries = Mage::getResourceModel('directory/country_collection')
									->loadData()
									->toOptionArray(false) */
							$country =  Mage::getStoreConfig('general/country/allow');
							$_countries = explode(",",$country);
							?>
							<select name="country" id="country">
								<option value=""><?php echo $this->__("-- Please Select --");?></option>
								<?php foreach($_countries as $_country): ?>
									<?php $country_name = Mage::app()->getLocale()->getCountryTranslation($_country); ?>
									<option value="<?php echo $_country ?>" <?php if($session->getWeeCountry() == $_country) echo "selected"; ?>>
										<?php echo $country_name; ?>
									</option>
								<?php endforeach; ?>
							</select>
                     </td>
                  </tr>
                  <?php /* <tr>
                     <td class="label"><label for="year"><?php echo $this->__("Year");?></label></td>
                     <td class="value">
						<select name="year" id="year" class=" select multiselect store_switcher" multiple="multiple">
							<option value="all"><?php echo $this->__("All");?></option>
							<?php
							for($j=date('Y')-20;$j<=date('Y');$j++)
							{
							echo "<option value='".$j."'>".$j."</option>";
							}
							?>
						</select>
                     </td>
                  </tr> */ ?>
                  <!--tr>
                     <td class="label"><label for="sales_report_period_type">Period</label></td>
                     <td class="value">
                        <select id="sales_report_period_type" name="period_type" title="Period" class=" select">
                           <option value="day">Day</option>
                           <option value="month">Month</option>
                           <option value="year">Year</option>
                        </select>
                     </td>
                  </tr-->
				  <?php 
					$baseUrl = Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL);
					$imgUrl = $baseUrl.'skin/adminhtml/default/default/images/grid-cal.gif'
					?>
                  <tr>
                     <td class="label"><label for="sales_report_from"><?php echo $this->__("From");?> <span class="required">*</span></label></td>
                     <td class="value">
                        <input name="report_from" id="sales_report_from" value="<?php echo $session->getReportFrom(); ?>" title="From" type="text" class="  input-text" style="width:110px !important;"> <img src="<?php echo $imgUrl; ?>" alt="" class="v-middle" id="sales_report_from_trig" title="Select Date" style="">
                        <script type="text/javascript">
                           //<![CDATA[
                               Calendar.setup({
                                   inputField: "sales_report_from",
                                   ifFormat: "%m/%e/%Y",
                                   showsTime: false,
                                   button: "sales_report_from_trig",
                                   align: "Bl",
                                   singleClick : true
                               });
                           //]]>
                        </script>            
                     </td>
                  </tr>
                  <tr>
                     <td class="label"><label for="sales_report_to"><?php echo $this->__("To");?> <span class="required">*</span></label></td>
                     <td class="value">
                        <input name="report_to" id="sales_report_to" value="<?php echo $session->getReportTo(); ?>" title="To" type="text" class="  input-text" style="width:110px !important;"> <img src="<?php echo $imgUrl; ?>" alt="" class="v-middle" id="sales_report_to_trig" title="Select Date" style="">
                        <script type="text/javascript">
                           //<![CDATA[
                               Calendar.setup({
                                   inputField: "sales_report_to",
                                   ifFormat: "%m/%e/%Y",
                                   showsTime: false,
                                   button: "sales_report_to_trig",
                                   align: "Bl",
                                   singleClick : true
                               });
                           //]]>
                        </script>            
                     </td>
                  </tr>
				  <?php /*
				   <tr>
                     <td class="label"><label for="month"><?php echo $this->__("Month");?></label></td>
                     <td class="value">
						<select name="month" id="month" class=" select multiselect store_switcher" multiple="multiple">
							<option value="all"><?php echo $this->__("All");?></option>
							<?php $months = array(
										'1' => 'January',
										'2' => 'February',
										'3' => 'March',
										'4' => 'April',
										'5' => 'May',
										'6' => 'June',
										'7' => 'July',
										'8' => 'August',
										'9' => 'September',
										'10' => 'October',
										'11' => 'November',
										'12' => 'December',
									);
								foreach($months as $key => $month){
									?>
										<option value="<?php echo $key; ?>"><?php echo $this->__($month); ?></option> 
									<?php
								}
							?>
						</select>
                     </td>
                  </tr> */ ?>
                  
               </tbody>
            </table>
         </div>
      </div>
   </form>
</div>